language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test
services:
  - postgresql
env:
  global:
    - TRAVIS_BUILD=true
    - DB=postgres
after_success:
    - coveralls
