# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160217_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='edits/', verbose_name='img')),
                ('effect', models.CharField(max_length=50)),
                ('parent_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Picture')),
            ],
        ),
    ]
