# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_edits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='edits',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edits',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 22, 15, 49, 14, 448886, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
