# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160215_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 15, 9, 22, 49, 165423, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 9, 23, 15, 948774, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
