# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160215_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_created']},
        ),
    ]
