# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160216_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
